# TERRAGON SDLC - Production Deployment Configuration
# Autonomous neuromorphic gas detection system
apiVersion: v1
kind: ConfigMap
metadata:
  name: bioneuro-olfactory-config
  namespace: terragon-production
data:
  # System Configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  METRICS_ENABLED: "true"
  HEALTH_CHECK_INTERVAL: "30"
  
  # Neuromorphic Processing
  NEURON_COUNT: "1000"
  SPIKE_THRESHOLD: "0.8"
  MEMBRANE_TIME_CONSTANT: "20.0"
  REFRACTORY_PERIOD: "2.0"
  
  # Scaling Configuration
  MIN_WORKERS: "2"
  MAX_WORKERS: "20"
  SCALING_THRESHOLD: "0.7"
  CACHE_SIZE_MB: "512"
  
  # Security
  ENABLE_TLS: "true"
  API_RATE_LIMIT: "1000"
  AUTH_REQUIRED: "true"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bioneuro-olfactory-system
  namespace: terragon-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bioneuro-olfactory
  template:
    metadata:
      labels:
        app: bioneuro-olfactory
    spec:
      containers:
      - name: neuromorphic-processor
        image: terragon/bioneuro-olfactory:v3.0
        ports:
        - containerPort: 8080
        env:
        - name: PYTHONPATH
          value: "/app"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: bioneuro-olfactory-service
  namespace: terragon-production
spec:
  selector:
    app: bioneuro-olfactory
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bioneuro-olfactory-hpa
  namespace: terragon-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bioneuro-olfactory-system
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80